; Gitea Configuration File
; This file is auto-generated by Terraform

APP_NAME = Gitea: Git with a cup of tea
RUN_USER = git
RUN_MODE = prod

[database]
DB_TYPE  = sqlite3
PATH     = /data/gitea/gitea.db

[repository]
ROOT = /data/gitea/repositories

[server]
DOMAIN       = ${domain}
HTTP_PORT    = 3000
ROOT_URL     = ${root_url}
DISABLE_SSH  = false
SSH_PORT     = 22
LFS_START_SERVER = true
APP_DATA_PATH = /data/gitea

[security]
INSTALL_LOCK   = true
SECRET_KEY     = ${secret_key}
INTERNAL_TOKEN = ${internal_token}

[service]
REGISTER_EMAIL_CONFIRM = false
ENABLE_NOTIFY_MAIL     = false
DISABLE_REGISTRATION   = false
ENABLE_CAPTCHA         = false
REQUIRE_SIGNIN_VIEW    = false
DEFAULT_KEEP_EMAIL_PRIVATE = true
DEFAULT_ALLOW_CREATE_ORGANIZATION = true
DEFAULT_ENABLE_TIMETRACKING = true

[oauth2]
ENABLE = true

[oauth2_client]
ENABLE                    = true
ENABLE_AUTO_REGISTRATION  = true
REGISTER_EMAIL_CONFIRM    = false
ACCOUNT_LINKING          = auto

[openid]
ENABLE_OPENID_SIGNIN = false
ENABLE_OPENID_SIGNUP = false

[log]
MODE      = console
LEVEL     = info
ROOT_PATH = /data/gitea/log

[picture]
AVATAR_UPLOAD_PATH = /data/gitea/avatars
REPOSITORY_AVATAR_UPLOAD_PATH = /data/gitea/repo-avatars

[attachment]
PATH = /data/gitea/attachments

[lfs]
PATH = /data/gitea/lfs

[session]
PROVIDER = file
PROVIDER_CONFIG = /data/gitea/sessions

[indexer]
ISSUE_INDEXER_PATH = /data/gitea/indexers/issues.bleve
REPO_INDEXER_PATH = /data/gitea/indexers/repos.bleve

[cache]
ENABLED = true
ADAPTER = memory

[mailer]
ENABLED = false

; OAuth providers must be configured through the UI or CLI after deployment
; The OAuth2 functionality is enabled above