on:
  workflow_dispatch:
    inputs:
      image:
        description: 'Image to test'
        required: true

jobs:
  test-image:
    runs-on: ubuntu-latest
    steps:
      - uses: chainguard-dev/actions/setup-chainctl@main
        with:
          identity: 7bf08061e47a927f78ffa39cd6393f4a83ec6eb7/aa8f8890af6747f9
      - run: |
          docker pull ${{ github.event.inputs.image }}
